# NumPy

Numpy es una librería que ofrece arreglos multidimencionales con los que podemos ejecutar operaciones de tipo matemático, lógicas, ordenamiento, etc. La ventaja es que estas operaciones matriciales se realizan a gran velocidad (es como tener un MatLab dentro de python). Es muy rápido porque realiza una precompilación en C, por esa razón es una librería muy utilizada en Ciencia de Datos e Inteligencia Artificial.   

In [1]:
import numpy as np

### Creando arreglos Array 

In [4]:
# Creando un array de numpy (sustituye a la lista de python y a la serie de Pandas)
arreglo1d = np.array([1,2,3])
arreglo1d, type(arreglo1d)

(array([1, 2, 3]), numpy.ndarray)

In [6]:
# Creando una matriz de numpy (sustituye a la lista de listas de python, pero no al DataFrame de Pandas, pues éste maneja nombres de columnas)
array2d = np.array([[1,2,3],
                    [0.5,0.6,0.9]])
array2d, type(array2d)

(array([[1. , 2. , 3. ],
        [0.5, 0.6, 0.9]]),
 numpy.ndarray)

In [7]:
# Array de 3 dimenciones (observe que se trata de un arreglo de arreglos (matriz), en el que cada elemento 
# individual de la matriz en si mismo contiene más arrays)
# Si lo analizamos como si se tratara de un objeto 3D con shape encontraremos (filas,columnas,anchura)

array3d = np.array([[[1,2,3],
                     [4,5,6]],
                     [[1,2,3],
                     [4,5,6]]])

array3d, array3d.shape

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 (2, 2, 3))

In [8]:
# Observando la forma de los arreglos creados.

arreglo1d.shape, array2d.shape, array3d.shape


((3,), (2, 3), (2, 2, 3))

In [9]:
# Para saber el número de dimensiones de los arreglos 

arreglo1d.ndim, array2d.ndim, array3d.ndim

(1, 2, 3)

In [13]:
# Arreglo con solo unos con np.ones((filas,columnas)) 
array_unos = np.ones((3,7))
array_unos

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [14]:
# Arreglo con solo unos con np.ones((filas,columnas)) 
array_ceros = np.zeros((3,7))
array_ceros

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [17]:
# Arreglo con valores en un rango dado y especificando el salto 
array_rango = np.arange(0,10,2)
array_rango

array([0, 2, 4, 6, 8])

In [18]:
# Array con valores random en un rango dado y especificando las dimenciones del arreglo
array_random = np.random.randint(0,10, size=(3,7))
array_random

array([[5, 6, 3, 4, 0, 8, 1],
       [0, 1, 3, 0, 0, 0, 9],
       [4, 7, 8, 2, 9, 3, 1]])

In [27]:
# Otra forma de crear array con valores random de 0 a 1 y especificando las dimenciones del arreglo
array_random = np.random.random(size=(3,7))
array_random # Los valores serán diferentes en cada ejecución

array([[0.6976312 , 0.06022547, 0.66676672, 0.67063787, 0.21038256,
        0.1289263 , 0.31542835],
       [0.36371077, 0.57019677, 0.43860151, 0.98837384, 0.10204481,
        0.20887676, 0.16130952],
       [0.65310833, 0.2532916 , 0.46631077, 0.24442559, 0.15896958,
        0.11037514, 0.65632959]])

In [25]:
# Array con valores random según una semilla dada, serán random solo en la primera ejecución, luego serán los mismos
np.random.seed(0) # Los randoms que se crearán dentro de la celda tendrán relación a la semilla
array_random4 = np.random.random(size=(3,7))
array_random4

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
        0.64589411, 0.43758721],
       [0.891773  , 0.96366276, 0.38344152, 0.79172504, 0.52889492,
        0.56804456, 0.92559664],
       [0.07103606, 0.0871293 , 0.0202184 , 0.83261985, 0.77815675,
        0.87001215, 0.97861834]])

### Operaciones con arreglos (array)

In [34]:
# Creamos una matriz 2x2 de números aleatorios con una semilla 
np.random.seed(0)
array1 = np.random.randint(0,10,size=(2,2))
array1, array1.shape 

(array([[5, 0],
        [3, 3]]),
 (2, 2))

In [33]:
# Creamos otra matriz 2x2 de números aleatorios con una semilla  
np.random.seed(3)
array2 = np.random.randint(0,10,size=(2,2))
array2, array1.shape 

(array([[8, 9],
        [3, 8]]),
 (2, 2))

In [35]:
array3 = array1 + array2

array3 # Se trata de la suma posición a posición llamada broadcasting 

array([[13,  9],
       [ 6, 11]])

In [32]:
# Creamos un arreglo con datos random y tridimencional 
np.random.seed(5)

array4 = np.random.randint(0,10,size=(2,2,3))

array4

array([[[3, 6, 6],
        [0, 9, 8]],

       [[4, 7, 0],
        [0, 7, 1]]])

In [36]:
# Tratamos de multiplicar los array y veremos un error pues necesitan tener las mismas dimenciones
# pero esto se puede arreglar 

array5 = array2 + array4

array5

ValueError: operands could not be broadcast together with shapes (2,2) (2,2,3) 

In [ ]:
# Verificamos las dimenciones del array 

array2.shape